### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by mattdesl** [rollup/three-jsnext#1]
Trying to test this out :smile:

Get the following on `npm install`

```
evalmachine.<anonymous>:761
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/projects/oss/three-jsnext/three.js/src'
    at Error (native)
    at Object.fs.readdirSync (evalmachine.<anonymous>:761:18)
    at processdir (/projects/oss/three-jsnext/node_modules/sander/dist/sander.js:665:15)
    at lsrSync (/projects/oss/three-jsnext/node_modules/sander/dist/sander.js:676:2)
    at exports.default (/projects/oss/three-jsnext/scripts/generate/src/index.js:14:16)
    at Object.<anonymous> (/projects/oss/three-jsnext/scripts/generate/index.js:3:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Darwin 14.0.0
npm ERR! argv "/Users/matt/.nvm/versions/node/v0.12.7/bin/node" "/Users/matt/.nvm/versions/node/v0.12.7/bin/npm" "run" "generate"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! three-jsnext@0.2.0 generate: `node scripts/generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the three-jsnext@0.2.0 generate script 'node scripts/generate'.
npm ERR! This is most likely a problem with the three-jsnext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/generate
npm ERR! You can get their info via:
npm ERR!     npm owner ls three-jsnext
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /projects/oss/three-jsnext/npm-debug.log

npm ERR! Darwin 14.0.0
npm ERR! argv "/Users/matt/.nvm/versions/node/v0.12.7/bin/node" "/Users/matt/.nvm/versions/node/v0.12.7/bin/npm" "run" "build"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! three-jsnext@0.2.0 build: `npm run generate && rollup -i src/index.js -o dist/three.js -f umd -n THREE && uglifyjs -c -m -o dist/three.min.js -- dist/three.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the three-jsnext@0.2.0 build script 'npm run generate && rollup -i src/index.js -o dist/three.js -f umd -n THREE && uglifyjs -c -m -o dist/three.min.js -- dist/three.js'.
npm ERR! This is most likely a problem with the three-jsnext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run generate && rollup -i src/index.js -o dist/three.js -f umd -n THREE && uglifyjs -c -m -o dist/three.min.js -- dist/three.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls three-jsnext
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /projects/oss/three-jsnext/npm-debug.log
npm ERR! Test failed.  See above for more details.

npm ERR! Darwin 14.0.0
npm ERR! argv "/Users/matt/.nvm/versions/node/v0.12.7/bin/node" "/Users/matt/.nvm/versions/node/v0.12.7/bin/npm" "i"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! three-jsnext@0.2.0 prepublish: `npm test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the three-jsnext@0.2.0 prepublish script 'npm test'.
npm ERR! This is most likely a problem with the three-jsnext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm test
npm ERR! You can get their info via:
npm ERR!     npm owner ls three-jsnext
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /projects/oss/three-jsnext/npm-debug.log
```

**Comment by Rich-Harris** [comment]
Ha, whoops! Well it _did_ work... looking into it

**Comment by Rich-Harris** [comment]
Did you run `npm run update-three`? It looks like it can't find the source code. Also I ran into a parse error while uglifying, updating a couple of deps seemed to do the trick, so if you pull and `npm update` hopefully it will work
