### ISSUE TITLE
building fails

### ISSUE THREAD

**Issue by Dev1an** [rollup/three-jsnext#8]
When I try to build, I get this

```
> three-jsnext@0.3.0 prepublish /private/tmp/three/node_modules/three-jsnext
> npm test


> three-jsnext@0.3.0 pretest /private/tmp/three/node_modules/three-jsnext
> npm run build


> three-jsnext@0.3.0 build /private/tmp/three/node_modules/three-jsnext
> npm run generate && npm run bundle && uglifyjs -c -m -o build/three.min.js -- build/three.js


> three-jsnext@0.3.0 generate /private/tmp/three/node_modules/three-jsnext
> node scripts/generate

import { WrapAroundEnding, ZeroCurvatureEnding, ZeroSlopeEnding, LoopPingPong, LoopOnce, LoopRepeat } from '../constants';

/**
 *
 * Action provided by AnimationMixer for scheduling clip playback on specific
 * objects.
 *
 * @author Ben Houston / http://clara.io/
 * @author David Sarno / http://lighthaus.us/
 * @author tschw
 *
 */

function AnimationAction( mixer, clip, localRoot ) {

    this._mixer = mixer;
    this._clip = clip;
    this._localRoot = localRoot || null;

    var tracks = clip.tracks,
        nTracks = tracks.length,
        interpolants = new Array( nTracks );

    var interpolantSettings = {
            endingStart:    ZeroCurvatureEnding,
            endingEnd:      ZeroCurvatureEnding
    };

    for ( var i = 0; i !== nTracks; ++ i ) {

        var interpolant = tracks[ i ].createInterpolant( null );
        interpolants[ i ] = interpolant;
        interpolant.settings = interpolantSettings;

    }

    this._interpolantSettings = interpolantSettings;

    this._interpolants = interpolants;  // bound by the mixer

    // inside: P/private/tmp/three/node_modules/three-jsnext/scripts/generate/src/Module.js:101
            throw err;
            ^

SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
    at Parser.pp$4.raise (/private/tmp/three/node_modules/three-jsnext/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$1.parseStatement (/private/tmp/three/node_modules/three-jsnext/node_modules/acorn/dist/acorn.js:717:16)
    at Parser.pp$1.parseTopLevel (/private/tmp/three/node_modules/three-jsnext/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/private/tmp/three/node_modules/three-jsnext/node_modules/acorn/dist/acorn.js:516:17)
    at parse (/private/tmp/three/node_modules/three-jsnext/node_modules/acorn/dist/acorn.js:3098:39)
    at new Module (/private/tmp/three/node_modules/three-jsnext/scripts/generate/src/Module.js:97:15)
    at files.map.file (/private/tmp/three/node_modules/three-jsnext/scripts/generate/src/index.js:35:18)
    at Array.map (native)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "generate"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! three-jsnext@0.3.0 generate: `node scripts/generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the three-jsnext@0.3.0 generate script 'node scripts/generate'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the three-jsnext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/generate
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs three-jsnext
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls three-jsnext
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/three/node_modules/three-jsnext/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! three-jsnext@0.3.0 build: `npm run generate && npm run bundle && uglifyjs -c -m -o build/three.min.js -- build/three.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the three-jsnext@0.3.0 build script 'npm run generate && npm run bundle && uglifyjs -c -m -o build/three.min.js -- build/three.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the three-jsnext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run generate && npm run bundle && uglifyjs -c -m -o build/three.min.js -- build/three.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs three-jsnext
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls three-jsnext
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/three/node_modules/three-jsnext/npm-debug.log
npm ERR! Test failed.  See above for more details.

npm WARN three-jsnext@0.3.0 No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! three-jsnext@0.3.0 prepublish: `npm test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the three-jsnext@0.3.0 prepublish script 'npm test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the three-jsnext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs three-jsnext
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls three-jsnext
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/three/node_modules/three-jsnext/npm-debug.log
```

**Comment by Rich-Harris** [comment]
[r80 uses ES modules](https://github.com/mrdoob/three.js/pull/9310), which means this project is no longer necessary! You should use the official source code directly.
